/**
 * 配置项中文说明，来源：https://wiki.metacubex.one/config/
 * 说明为功能简介，非示例或补充备注。
 */

/** 完整路径 → 说明（与 schema 扁平 path 一致） */
export const WIKI_DESCRIPTIONS_BY_PATH: Record<string, string> = {
  port: "HTTP(S) 代理监听端口",
  "socks-port": "SOCKS5 代理监听端口",
  "mixed-port": "HTTP(S) 与 SOCKS 混合代理端口",
  "redir-port": "透明代理端口（Linux / macOS）",
  "tproxy-port": "TProxy 透明代理端口（Linux）",
  "allow-lan": "是否允许局域网设备连接代理",
  "bind-address": "允许局域网时绑定的监听地址",
  authentication: "HTTP(S)/SOCKS/Mixed 代理的用户名密码认证",
  "skip-auth-prefixes": "允许跳过代理认证的 IP 段",
  "lan-allowed-ips": "允许连接的 IP 段（allow-lan 为 true 时生效）",
  "lan-disallowed-ips": "禁止连接的 IP 段（优先级高于白名单）",
  "find-process-mode": "进程匹配模式（always / strict / off）",
  mode: "运行模式（rule 规则 / global 全局 / direct 直连）",
  "log-level": "内核日志输出级别",
  ipv6: "是否允许内核处理 IPv6 流量",
  "geox-url": "自定义 GeoIP / GeoSite / MMDB 下载地址",
  "geox-url.geoip": "GeoIP 数据文件下载地址",
  "geox-url.geosite": "GeoSite 数据文件下载地址",
  "geox-url.mmdb": "GeoIP MMDB 数据文件下载地址",
  "geox-url.asn": "GeoIP ASN 数据文件下载地址",
  "geo-auto-update": "是否自动更新 Geo 数据",
  "geo-update-interval": "Geo 数据自动更新间隔（小时）",
  "geosite-matcher": "GeoSite 匹配器实现（succinct / mph）",
  "geodata-mode": "GeoIP 数据格式（true 为 dat，false 为 mmdb）",
  "geodata-loader": "Geo 文件加载模式（standard / memconservative）",
  "global-ua": "下载外部资源时使用的 User-Agent",
  "etag-support": "外部资源下载是否启用 ETag",
  tls: "RESTful API HTTPS 使用的 TLS 配置",
  "tls.certificate": "TLS 证书（PEM 内容或文件路径）",
  "tls.private-key": "TLS 私钥（PEM 内容或文件路径）",
  "tls.ech-key": "TLS ECH 密钥（填写后启用 ECH）",
  "tls.client-auth-type": "TLS 客户端证书校验类型",
  "tls.client-auth-cert": "TLS 客户端证书",
  "tls.custom-certifactes": "额外信任的 TLS 证书列表",
  "external-controller": "RESTful API 监听地址",
  "external-controller-tls": "RESTful API HTTPS 监听地址",
  secret: "RESTful API 访问密钥",
  "external-controller-cors": "RESTful API 的 CORS 配置",
  "external-controller-cors.allow-origins": "CORS 允许的 Origin 列表",
  "external-controller-cors.allow-private-network": "是否允许私有网络访问 CORS",
  "external-controller-unix": "RESTful API Unix Socket 监听地址",
  "external-controller-pipe": "RESTful API Windows 命名管道地址",
  "external-doh-server": "在 API 端口上提供的 DoH 服务路径",
  "external-ui": "外部 Web UI 静态资源目录",
  "external-ui-name": "外部 Web UI 子目录名称",
  "external-ui-url": "自定义外部用户界面下载地址",
  "tcp-concurrent": "启用 TCP 并发连接（使用 DNS 解析出的全部 IP）",
  "interface-name": "出站流量使用的网卡名称",
  "routing-mark": "Linux 出站连接的 fwmark 标记",
  "disable-keep-alive": "是否禁用 TCP Keep Alive",
  "keep-alive-idle": "TCP Keep Alive 最大空闲时间（秒）",
  "keep-alive-interval": "TCP Keep Alive 探测间隔（秒）",
  "unified-delay": "统一延迟测速（消除不同节点握手差异）",
  "global-client-fingerprint": "全局 TLS 客户端指纹（已弃用，建议在代理节点配置）",
  profile: "配置持久化选项",
  "profile.store-selected": "是否保存策略组选择状态",
  "profile.store-fake-ip": "是否保存 Fake-IP 映射表",
  hosts: "静态 Hosts 映射（类似 /etc/hosts）",
  experimental: "实验性选项",
  "experimental.quic-go-disable-gso": "禁用 QUIC-go 的 GSO 优化",
  tun: "TUN 虚拟网卡入站",
  "tun.enable": "是否启用 TUN",
  "tun.stack": "TUN 协议栈（system / gvisor / mixed）",
  "tun.device": "TUN 网卡名称",
  "tun.mtu": "TUN 最大传输单元",
  "tun.gso": "是否启用 GSO（仅 Linux）",
  "tun.gso-max-size": "GSO 数据块最大长度",
  "tun.dns-hijack": "DNS 劫持地址列表",
  "tun.auto-route": "是否自动设置全局路由",
  "tun.auto-redirect": "是否自动重定向 TCP（Linux，需 auto-route）",
  "tun.auto-detect-interface": "是否自动检测出站网卡",
  "tun.strict-route": "启用 auto-route 时的严格路由",
  "tun.route-address": "auto-route 时自定义路由网段",
  "tun.route-exclude-address": "auto-route 时排除的路由网段",
  "tun.route-address-set": "加入防火墙的路由规则集（不命中则绕过）",
  "tun.route-exclude-address-set": "加入防火墙的排除规则集（命中则绕过）",
  "tun.endpoint-independent-nat": "是否启用独立于端点的 NAT",
  "tun.inet6-address": "TUN IPv6 地址",
  "tun.udp-timeout": "UDP NAT 过期时间（秒）",
  "tun.iproute2-table-index": "auto-route 使用的路由表索引",
  "tun.iproute2-rule-index": "auto-route 使用的规则起始索引",
  "tun.include-interface": "限制参与路由的网卡",
  "tun.exclude-interface": "排除参与路由的网卡",
  "tun.include-uid": "仅路由指定 Linux UID 的流量",
  "tun.exclude-uid": "排除指定 Linux UID 的流量",
  "tun.include-uid-range": "仅路由指定 UID 范围的流量",
  "tun.exclude-uid-range": "排除指定 UID 范围的流量",
  "tun.include-android-user": "仅路由指定 Android 用户的流量",
  "tun.include-package": "仅路由指定 Android 应用的流量",
  "tun.exclude-package": "排除指定 Android 应用的流量",
  "tun.disable-icmp-forwarding": "是否禁用 ICMP 转发",
  sniffer: "域名嗅探配置",
  "sniffer.enable": "是否启用域名嗅探",
  "sniffer.force-dns-mapping": "对 redir-host 流量强制嗅探",
  "sniffer.parse-pure-ip": "对未获取域名的流量强制嗅探",
  "sniffer.override-destination": "是否用嗅探结果作为实际访问目标",
  "sniffer.force-domain": "强制嗅探的域名列表",
  "sniffer.skip-domain": "跳过嗅探的域名列表",
  "sniffer.skip-src-address": "跳过嗅探的来源 IP 段",
  "sniffer.skip-dst-address": "跳过嗅探的目标 IP 段",
  tunnels: "端口转发隧道列表",
  dns: "DNS 模块配置",
  "dns.enable": "是否启用内置 DNS（关闭则使用系统 DNS）",
  "dns.cache-algorithm": "DNS 缓存算法（lru / arc）",
  "dns.prefer-h3": "DoH 是否优先使用 HTTP/3",
  "dns.listen": "DNS 服务监听地址",
  "dns.ipv6": "DNS 是否解析并回应 AAAA",
  "dns.ipv6-timeout": "IPv6 DNS 解析超时（秒）",
  "dns.enhanced-mode": "DNS 处理模式（fake-ip / redir-host）",
  "dns.fake-ip-range": "Fake-IP IPv4 地址池",
  "dns.fake-ip-range6": "Fake-IP IPv6 地址池",
  "dns.fake-ip-filter": "不使用 Fake-IP 的域名或规则",
  "dns.fake-ip-filter-mode": "Fake-IP 过滤模式（blacklist / whitelist / rule）",
  "dns.fake-ip-ttl": "Fake-IP 查询结果的 TTL",
  "dns.use-hosts": "是否使用配置中的 hosts 回应",
  "dns.use-system-hosts": "是否查询系统 hosts",
  "dns.respect-rules": "DNS 连接是否遵守路由规则",
  "dns.default-nameserver": "用于解析 DNS 服务器域名的 DNS（须为 IP）",
  "dns.nameserver": "默认域名解析服务器列表",
  "dns.nameserver-policy": "指定域名使用的 DNS 服务器",
  "dns.fallback": "后备域名解析服务器（通常用于境外 DNS）",
  "dns.fallback-filter": "后备 DNS 结果筛选条件",
  "dns.fallback-filter.geoip": "是否用 GeoIP 判断污染",
  "dns.fallback-filter.geoip-code": "视为可信的国家代码",
  "dns.fallback-filter.geosite": "视为污染的 GeoSite 列表",
  "dns.fallback-filter.ipcidr": "视为污染的 IP 段",
  "dns.fallback-filter.domain": "视为污染的域名列表",
  "dns.proxy-server-nameserver": "仅用于解析代理节点域名的 DNS",
  "dns.proxy-server-nameserver-policy": "代理节点域名的 DNS 策略",
  "dns.direct-nameserver": "直连出口使用的 DNS",
  "dns.direct-nameserver-follow-policy": "直连 DNS 是否遵守 nameserver-policy",
  "dns.geoip": "DNS 模块内 GeoIP 开关（fallback-filter 子项）",
  "dns.geoip-code": "DNS 模块内 GeoIP 国家代码",
  proxies: "出站代理节点列表",
  "proxy-groups": "代理策略组列表",
  "proxy-providers": "代理集合提供者列表",
  "rule-providers": "规则集提供者列表",
  "rule-providers.path": "本地规则集路径",
  "rule-providers.url": "远程规则集地址",
  "rule-providers.interval": "更新间隔（秒）",
  rules: "路由规则列表",
  "sub-rules": "子规则集映射",
  listeners: "入站监听器列表",
  ntp: "NTP 时间同步配置",
  "ntp.enable": "是否启用 NTP 服务",
  "ntp.write-to-system": "是否同步至系统时间（需 root 或管理员权限）",
  "ntp.server": "NTP 服务地址",
  "ntp.port": "NTP 服务端口",
  "ntp.interval": "同步时间间隔（分钟）",
  https: "HTTPS 相关实验配置",
  "ss-config": "Shadowsocks 默认配置片段",
  "vmess-config": "VMess 默认配置片段",
};

/** 字段名 → 说明（用于 proxies.*、listeners.* 等动态路径） */
export const WIKI_DESCRIPTIONS_BY_KEY: Record<string, string> = {
  name: "名称",
  type: "类型",
  server: "服务器地址",
  port: "端口",
  uuid: "用户 ID",
  password: "密码",
  cipher: "加密方式",
  plugin: "插件",
  udp: "是否启用 UDP",
  "udp-over-tcp": "是否使用 UDP over TCP",
  "ip-version": "IP 版本偏好",
  "client-fingerprint": "TLS 客户端指纹",
  alpn: "TLS ALPN 列表",
  sni: "TLS SNI",
  "skip-cert-verify": "是否跳过 TLS 证书验证",
  "fingerprint": "TLS 指纹",
  network: "传输协议",
  tls: "是否启用 TLS",
  "reality-opts": "REALITY 选项",
  "ws-opts": "WebSocket 选项",
  "h2-opts": "HTTP/2 选项",
  "grpc-opts": "gRPC 选项",
  "smux-opts": "Smux 多路复用选项",
  "ech-opts": "ECH 选项",
  "ech-opts.enable": "是否启用 ECH",
  "ech-opts.query-server-name": "ECH 查询用的服务器名",
  "reality-opts.public-key": "REALITY 公钥",
  "reality-opts.short-id": "REALITY Short ID",
  "ws-opts.path": "WebSocket 路径",
  "ws-opts.headers": "WebSocket 请求头",
  "grpc-opts.grpc-service-name": "gRPC 服务名",
  "h2-opts.path": "HTTP/2 路径",
  "h2-opts.host": "HTTP/2 Host",
  proxies: "策略组引用的代理或组",
  "use": "引用的代理集合",
  "include-all": "是否包含全部代理",
  "include-all-proxies": "是否包含全部节点",
  "include-all-providers": "是否包含全部提供者",
  filter: "过滤表达式",
  "exclude-filter": "排除过滤表达式",
  "exclude-type": "排除的代理类型",
  icon: "策略组图标 URL",
  hidden: "是否在面板中隐藏",
  interval: "测速或检查间隔（秒）",
  tolerance: "延迟容差（毫秒）",
  lazy: "是否惰性测速",
  url: "健康检查或测速 URL",
  "max-failed-times": "最大失败次数",
  "expected-status": "健康检查期望 HTTP 状态码",
  "disable-udp": "是否禁用 UDP",
  "routing-mark": "出站 fwmark",
  "dialer-proxy": "发起连接使用的代理",
  "interface-name": "出站网卡",
  path: "路径",
  "health-check": "健康检查配置",
  "health-check.enable": "是否启用健康检查",
  "health-check.url": "健康检查 URL",
  "health-check.interval": "健康检查间隔",
  "health-check.lazy": "是否惰性健康检查",
  "health-check.expected-status": "健康检查期望状态码",
  behavior: "规则集类型",
  format: "规则集文件格式",
  payload: "内联规则集内容",
  "size-limit": "下载大小限制",
  "download-detour": "下载使用的代理",
  "proxy": "使用的代理",
  enable: "是否启用",
  listen: "监听地址",
  stack: "协议栈",
  rule: "单条路由规则",
  "network-type": "网络类型",
  "destination-override": "是否覆盖目标地址",
  "force-dns-mapping": "是否强制 DNS 映射",
  "parse-pure-ip": "是否解析纯 IP 连接",
  "override-destination": "是否覆盖连接目标",
  "sniff": "按协议的嗅探配置",
  "force-domain": "强制嗅探域名",
  "skip-domain": "跳过嗅探域名",
  "inbound": "入站名称",
  "outbound": "出站名称",
  "target": "转发目标",
  "target-port": "转发目标端口",
  "server-name": "TLS 服务名",
  "private-key": "私钥",
  certificate: "证书",
  "congestion-controller": "拥塞控制算法",
  "max-idle-time": "最大空闲时间",
  "authentication-timeout": "认证超时",
  "max-udp-relay-packet-size": "UDP 中继最大包长",
  "enable-pure-downlink": "是否启用纯下行（关闭为带宽优化下行）",
  "support-x25519mlkem768": "是否启用 x25519mlkem768 密钥交换",
  "remote-dns-resolve": "是否由远端解析 DNS",
  disable: "是否禁用",
  "v2ray-http-opts": "V2Ray HTTP 伪装选项",
  "v2ray-http-opts.disable": "是否禁用 HTTP 伪装与隧道",
  "accept-routes": "是否接受路由",
  "allow-lan": "是否允许局域网",
  "bind-address": "绑定地址",
  "lan-allowed-ips": "局域网允许 IP 段",
  "lan-disallowed-ips": "局域网禁止 IP 段",
};
